osx_image: xcode8.3

dist: trusty
sudo: true

language: node_js
node_js: "8"

os:
  - linux
  - osx

script:
  - npm update music-api
  - node build

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - releases/*.deb
    - releases/*.dmg
    - releases/*.exe
  skip_cleanup: true

branches:
  only:
  - master
  
notifications:
  email: false