osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

script:
  - node build

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - releases/*.deb
    - releases/*.dmg
    - releases/*.exe
  skip_cleanup: true

branches:
  only:
  - master
  
notifications:
  email: false